### Create Products
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "sd",
  "description": "Latest 5G smartphone",
  "price": 12000,
  "categoryId": "1"
}

### GET Product
GET http://localhost:8080/api/products/1
Accept: application/json

### Create Category
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "def"
}


### GET Category
GET http://localhost:8080/api/categories/1
Accept: application/json

### GET All Categories
GET http://localhost:8080/api/categories
Accept: application/json

### Delete Category
DELETE http://localhost:8080/api/categories/2
Accept: application/json

### Create Product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "te",
  "description": "Phone category",
  "price": 22700,
  "categoryId": 4
}

### Get all products
GET http://localhost:8080/api/products
Content-Type: application/json

### Delete product
DELETE http://localhost:8080/api/products/1

### Update product
PUT http://localhost:8080/api/products
Content-Type: application/json

{
  "id": 1,
  "name": "no might",
  "price": 23700,
  "description": "xyz",
  "categoryId": 2
}