### Create Products
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "smartphone",
  "description": "Latest 5G smartphone",
  "price": 12000,
  "categoryId": "1"
}

### GET Product
GET http://localhost:8080/api/products/1
Accept: application/json

### Create Category
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Phone"
}


### GET Category
GET http://localhost:8080/api/categories/1
Accept: application/json

### Delete Category
DELETE http://localhost:8080/api/categories/2
Accept: application/json

### Create Product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "readme7",
  "description": "Phone category",
  "price": 22700,
  "categoryId": 1
}

